application: gtfs-data-exchange-hrd
version: 7
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: django
  version: "1.4"

handlers:
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  
- url: /googlefe9fe31f1c84a82e.html
  static_files: static/googlefe9fe31f1c84a82e.html
  upload: static/googlefe9fe31f1c84a82e.html

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  
- url: /static
  static_dir: static

- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: .*
  script: gtfs_data_exchange.py
  
skip_files: |
     ^(.*/)?(
     (contrib/.*)
     (app\.yaml)|
     (app\.yml)|
     (index\.yaml)|
     (index\.yml)|
     (#.*#)|
     (.*~)|
     (.*\.py[co])|
     (.*/RCS/.*)|
     (\..*)|
     (.*\.psd)|
     (.*lineform/.*)|
     (\.git.*)|
     (data/.*)
     )$